language: cpp
os:
#  - linux
#  - osx
  - windows 
  
before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install vswhere --pre      ; fi

script: 
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then powershell -c './bob.cmd build' ;fi
  - foo
  #- powershell -C '&"${Env:ProgramData}\chocolatey\bin\vswhere.exe"-products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath'
#  else ./bob.cmd