language: cpp
os:
#  - linux
#  - osx
  - windows 
  
before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install vswhere --pre      ; fi

script: 
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then powershell ./bob.cmd 
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then powershell "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
#  else ./bob.cmd