language: cpp
os:
#  - linux
#  - osx
  - windows 
  
before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install vswhere --pre      ; fi

script: 
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then powershell -c './bob.cmd' ;fi
  - powershell -C '${Env:SystemDrive}\Chocolatey\bin\vswhere.exe'
#  else ./bob.cmd