language: cpp
os:
#  - linux
#  - osx
  - windows 
  
before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install vswhere --pre      ; fi

script: 
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then pwsh -c './bob.cmd'
#  else ./bob.cmd